# Generated by Django 2.0.5 on 2018-05-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30, verbose_name='用户密码')),
                ('uuid', models.CharField(max_length=30, verbose_name='uuid')),
                ('token', models.CharField(max_length=30, verbose_name='token')),
                ('token_expired', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'user',
                'ordering': ('uuid',),
            },
        ),
    ]
