# Generated by Django 2.0.5 on 2018-05-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_im', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='token'),
        ),
    ]
