# Generated by Django 2.0.5 on 2018-05-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_im', '0002_auto_20180529_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(max_length=40, verbose_name='uuid'),
        ),
    ]
