# Generated by Django 2.0.5 on 2018-05-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_im', '0003_auto_20180529_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField()),
                ('friend_id', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_content', models.CharField(max_length=1000)),
                ('msg_content_type', models.CharField(choices=[('T', 'Text'), ('I', 'Img'), ('A', 'Audio'), ('V', 'Medio')], default='T', max_length=1)),
                ('msg_notice_type', models.CharField(choices=[('P', 'Private'), ('S', 'System'), ('G', 'Group')], default='P', max_length=1)),
                ('msg_sender', models.IntegerField()),
                ('msg_receiver', models.IntegerField()),
                ('msg_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.AutoField(default=100, primary_key=True, serialize=False),
        ),
    ]
