# Generated by Django 2.0.5 on 2018-05-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_im', '0006_auto_20180529_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='msg_receiver',
            new_name='msg_receiver_id',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='msg_sender',
            new_name='msg_sender_id',
        ),
        migrations.AlterField(
            model_name='message',
            name='msg_status',
            field=models.BooleanField(default=False),
        ),
    ]
