# Generated by Django 2.0.5 on 2018-05-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_im', '0008_auto_20180529_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.CharField(choices=[('W', 'wait'), ('D', 'done'), ('R', 'remove')], default='W', max_length=1),
        ),
    ]
