# Generated by Django 2.0.5 on 2018-05-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_im', '0009_auto_20180529_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.CharField(choices=[('W', 'wait'), ('A', 'Accept'), ('R', 'remove'), ('D', 'Decline')], default='W', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('owner_id', 'friend_id')},
        ),
    ]
