# Generated by Django 2.0.5 on 2018-05-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_im', '0010_auto_20180529_1837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('user_id',), 'verbose_name': 'user', 'verbose_name_plural': 'user'},
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='friend_id',
            new_name='receiver_id',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='owner_id',
            new_name='sender_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token_expired',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='token'),
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('sender_id', 'receiver_id')},
        ),
    ]
